<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

/**
 * Class AttributeValue
 * @package App\Models
 */

/**
 * [auto-gen-property]
 * @property int $id
 * @property int $attribute_id
 * @property string $value
 * @property string $code
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * [/auto-gen-property]
 *
 */
class AttributeValue extends Model
{
    use SoftDeletes;
    /**
     * The table associated with the model.
     *
     * @var string $table
     */
    protected $table = 'attribute_values';

    /**
     * The primary key for the model.
     *
     * @var string $primaryKey
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        # [auto-gen-attribute]
        'attribute_id',
        'value',
        'code',
        # [/auto-gen-attribute]
    ];

    public static $rules = [
        'attribute_id' => 'required|integer',
        'value' => 'required|string|max:255',
        'code' => 'string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
    ];

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public function attribute()
    {
        return $this->belongsTo(Attribute::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($query) {
            $query->code = Str::slug($query->value);
        });

        static::updating(function ($query) {
            $query->code = Str::slug($query->value);
        });
    }

    public function ProductAttributeValue()
    {
        return $this->hasMany(ProductAttributeValue::class, 'attribute_value_id', 'id');
    }
}
