<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * Class Attribute
 * @package App\Models
 */

/**
 * [auto-gen-property]
 * @property int $id
 * @property string $attribute_code
 * @property string $name
 * @property string $deleted_at
 * @property string $created_at
 * @property string $updated_at
 * [/auto-gen-property]
 *
 */
class Attribute extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string $table
     */
    protected $table = 'attributes';

    /**
     * The primary key for the model.
     *
     * @var string $primaryKey
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        # [auto-gen-attribute]
        'attribute_code',
        'name' ,
        # [/auto-gen-attribute]
    ];

    public static $rules = [
        'name' => 'required|string|max:255|unique:attributes,name',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($query) {
            $query->attribute_code = strtoupper(Str::slug($query->name));
        });

        static::updating(function ($query) {
            $query->attribute_code = strtoupper(Str::slug($query->name));
        });
    }
}
