<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;


/**
 * Class Blog
 * @package App\Models
 */

/**
 * [auto-gen-property]
 * @property int $id
 * @property string $title
 * @property int $star
 * @property string $slug
 * @property string $deleted_at
 * @property int $category_blog_id
 * @property string $created_at
 * @property string $updated_at
 * [/auto-gen-property]
 *
 */
class Blog extends Model
{
    use SoftDeletes;
    /**
     * The table associated with the model.
     *
     * @var string $table
     */
    protected $table = 'blog';

    /**
     * The primary key for the model.
     *
     * @var string $primaryKey
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        # [auto-gen-attribute]
        'title',
        'star',
        'slug',
        'default_image',
        'category_blog_id' ,
        'content',
        'description',
        'view'
        # [/auto-gen-attribute]
    ];

    public function blogCategory()
    {
        return $this->belongsTo(BlogCategory::class, 'category_blog_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($query) {
            $query->slug = Str::slug($query->title);
        });

        static::updating(function ($query) {
            $query->slug = Str::slug($query->title);
        });
    }
    
    public function seoContents()
    {
        return $this->hasOne(SeoContent::class, "entity_id", "id")->where("entity_type", SeoContent::SEO_NEWS);
    }
}
