<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class CategoryBrand
 * @package App\Models
 */

/**
 * [auto-gen-property]
 * @property int $id
 * @property int $category_id
 * @property int $brand_id
 * @property int $position
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * [/auto-gen-property]
 *
 */
class CategoryBrand extends Model
{
    use SoftDeletes;
    /**
     * The table associated with the model.
     *
     * @var string $table
     */
    protected $table = 'category_brands';

    /**
     * The primary key for the model.
     *
     * @var string $primaryKey
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        # [auto-gen-attribute]
        'category_id',
        'brand_id',
        'position',
        # [/auto-gen-attribute]
    ];

    public static $rules = [
        'category_id' => 'required|integer',
        'brand_id' => 'required|integer',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    public function brand()
    {
        return $this->hasOne(Brand::class, "id", "brand_id");
    }

    public function category()
    {
        return $this->hasOne(Category::class, "id", "category_id");
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($query) {
            $query->position = 0;
        });
    }
}
