<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;


/**
 * Class ProductManual
 * @package App\Models
 */

/**
 * [auto-gen-property]
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $slug
 * @property string $created_at
 * @property string $updated_at
 * [/auto-gen-property]
 *
 */
class ProductManual extends Model
{
    use SoftDeletes;
    /**
     * The table associated with the model.
     *
     * @var string $table
     */
    protected $table = 'product_manual';

    /**
     * The primary key for the model.
     *
     * @var string $primaryKey
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        # [auto-gen-attribute]
        'title',
        'content',
        'slug' ,
        # [/auto-gen-attribute]
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($query) {
            $query->slug = Str::slug($query->title);
        });

        static::updating(function ($query) {
            $query->slug = Str::slug($query->title);
        });
    }
}
